!!python/object/new:openood.utils.config.Config
state:
  dataset:
    name: mnist
    num_classes: 10
    image_size: 28
    pre_size: 28
    interpolation: bilinear
    normalization_type: mnist
    num_workers: 2
    num_gpus: 1
    num_machines: 1
    split_names: &id001
    - train
    - val
    - test
    train:
      dataset_class: ImglistDataset
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/mnist/train_mnist.txt
      batch_size: 128
      shuffle: true
    val:
      dataset_class: ImglistDataset
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/mnist/val_mnist.txt
      batch_size: 200
      shuffle: false
    test:
      dataset_class: ImglistDataset
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/mnist/test_mnist.txt
      batch_size: 200
      shuffle: false
  ood_dataset:
    name: mnist_ood
    num_classes: 10
    num_workers: 2
    num_gpus: 1
    num_machines: 1
    dataset_class: ImglistDataset
    batch_size: 128
    shuffle: false
    split_names: &id002
    - val
    - nearood
    - farood
    val:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/mnist/val_notmnist.txt
    nearood:
      datasets: &id003
      - notmnist
      - fashionmnist
      notmnist:
        data_dir: ./data/images_classic/
        imglist_pth: ./data/benchmark_imglist/mnist/test_notmnist.txt
      fashionmnist:
        data_dir: ./data/images_classic/
        imglist_pth: ./data/benchmark_imglist/mnist/test_fashionmnist.txt
    farood:
      datasets: &id004
      - texture
      - cifar10
      - tin
      - places365
      texture:
        data_dir: ./data/images_classic/
        imglist_pth: ./data/benchmark_imglist/mnist/test_texture.txt
      cifar10:
        data_dir: ./data/images_classic/
        imglist_pth: ./data/benchmark_imglist/mnist/test_cifar10.txt
      tin:
        data_dir: ./data/images_classic/
        imglist_pth: ./data/benchmark_imglist/mnist/test_tin.txt
      places365:
        data_dir: ./data/images_classic/
        imglist_pth: ./data/benchmark_imglist/mnist/test_places365.txt
  network:
    name: resnet50
    num_classes: 10
    image_size: 28
    pretrained: true
    checkpoint: ./imagenet_resnet50_base_e30_lr0.001_randaugment-2-9/s0/best_epoch27_acc0.7668.ckpt
    num_gpus: 1
  exp_name: mnist_resnet50_test_ood_ood_msp_default/s0/ood
  output_dir: ./results/
  save_output: true
  merge_option: default
  mark: default
  seed: 0
  num_gpus: 1
  num_workers: 2
  num_machines: 1
  machine_rank: 0
  preprocessor:
    name: base
  pipeline:
    name: test_ood
  trainer:
    name: base
  evaluator:
    name: ood
    ood_scheme: ood
  optimizer:
    name: sgd
    num_epochs: 60
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
  recorder:
    name: base
    save_all_models: false
    save_scores: true
    save_csv: true
  postprocessor:
    name: msp
    APS_mode: false
dictitems:
  dataset: !!python/object/new:openood.utils.config.Config
    state:
      name: mnist
      num_classes: 10
      image_size: 28
      pre_size: 28
      interpolation: bilinear
      normalization_type: mnist
      num_workers: 2
      num_gpus: 1
      num_machines: 1
      split_names: *id001
      train:
        dataset_class: ImglistDataset
        data_dir: ./data/images_classic/
        imglist_pth: ./data/benchmark_imglist/mnist/train_mnist.txt
        batch_size: 128
        shuffle: true
      val:
        dataset_class: ImglistDataset
        data_dir: ./data/images_classic/
        imglist_pth: ./data/benchmark_imglist/mnist/val_mnist.txt
        batch_size: 200
        shuffle: false
      test:
        dataset_class: ImglistDataset
        data_dir: ./data/images_classic/
        imglist_pth: ./data/benchmark_imglist/mnist/test_mnist.txt
        batch_size: 200
        shuffle: false
    dictitems:
      name: mnist
      num_classes: 10
      image_size: 28
      pre_size: 28
      interpolation: bilinear
      normalization_type: mnist
      num_workers: 2
      num_gpus: 1
      num_machines: 1
      split_names: *id001
      train: !!python/object/new:openood.utils.config.Config
        state:
          dataset_class: ImglistDataset
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/train_mnist.txt
          batch_size: 128
          shuffle: true
        dictitems:
          dataset_class: ImglistDataset
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/train_mnist.txt
          batch_size: 128
          shuffle: true
      val: !!python/object/new:openood.utils.config.Config
        state:
          dataset_class: ImglistDataset
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/val_mnist.txt
          batch_size: 200
          shuffle: false
        dictitems:
          dataset_class: ImglistDataset
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/val_mnist.txt
          batch_size: 200
          shuffle: false
      test: !!python/object/new:openood.utils.config.Config
        state:
          dataset_class: ImglistDataset
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/test_mnist.txt
          batch_size: 200
          shuffle: false
        dictitems:
          dataset_class: ImglistDataset
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/test_mnist.txt
          batch_size: 200
          shuffle: false
  ood_dataset: !!python/object/new:openood.utils.config.Config
    state:
      name: mnist_ood
      num_classes: 10
      num_workers: 2
      num_gpus: 1
      num_machines: 1
      dataset_class: ImglistDataset
      batch_size: 128
      shuffle: false
      split_names: *id002
      val:
        data_dir: ./data/images_classic/
        imglist_pth: ./data/benchmark_imglist/mnist/val_notmnist.txt
      nearood:
        datasets: *id003
        notmnist:
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/test_notmnist.txt
        fashionmnist:
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/test_fashionmnist.txt
      farood:
        datasets: *id004
        texture:
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/test_texture.txt
        cifar10:
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/test_cifar10.txt
        tin:
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/test_tin.txt
        places365:
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/test_places365.txt
    dictitems:
      name: mnist_ood
      num_classes: 10
      num_workers: 2
      num_gpus: 1
      num_machines: 1
      dataset_class: ImglistDataset
      batch_size: 128
      shuffle: false
      split_names: *id002
      val: !!python/object/new:openood.utils.config.Config
        state:
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/val_notmnist.txt
        dictitems:
          data_dir: ./data/images_classic/
          imglist_pth: ./data/benchmark_imglist/mnist/val_notmnist.txt
      nearood: !!python/object/new:openood.utils.config.Config
        state:
          datasets: *id003
          notmnist:
            data_dir: ./data/images_classic/
            imglist_pth: ./data/benchmark_imglist/mnist/test_notmnist.txt
          fashionmnist:
            data_dir: ./data/images_classic/
            imglist_pth: ./data/benchmark_imglist/mnist/test_fashionmnist.txt
        dictitems:
          datasets: *id003
          notmnist: !!python/object/new:openood.utils.config.Config
            state:
              data_dir: ./data/images_classic/
              imglist_pth: ./data/benchmark_imglist/mnist/test_notmnist.txt
            dictitems:
              data_dir: ./data/images_classic/
              imglist_pth: ./data/benchmark_imglist/mnist/test_notmnist.txt
          fashionmnist: !!python/object/new:openood.utils.config.Config
            state:
              data_dir: ./data/images_classic/
              imglist_pth: ./data/benchmark_imglist/mnist/test_fashionmnist.txt
            dictitems:
              data_dir: ./data/images_classic/
              imglist_pth: ./data/benchmark_imglist/mnist/test_fashionmnist.txt
      farood: !!python/object/new:openood.utils.config.Config
        state:
          datasets: *id004
          texture:
            data_dir: ./data/images_classic/
            imglist_pth: ./data/benchmark_imglist/mnist/test_texture.txt
          cifar10:
            data_dir: ./data/images_classic/
            imglist_pth: ./data/benchmark_imglist/mnist/test_cifar10.txt
          tin:
            data_dir: ./data/images_classic/
            imglist_pth: ./data/benchmark_imglist/mnist/test_tin.txt
          places365:
            data_dir: ./data/images_classic/
            imglist_pth: ./data/benchmark_imglist/mnist/test_places365.txt
        dictitems:
          datasets: *id004
          texture: !!python/object/new:openood.utils.config.Config
            state:
              data_dir: ./data/images_classic/
              imglist_pth: ./data/benchmark_imglist/mnist/test_texture.txt
            dictitems:
              data_dir: ./data/images_classic/
              imglist_pth: ./data/benchmark_imglist/mnist/test_texture.txt
          cifar10: !!python/object/new:openood.utils.config.Config
            state:
              data_dir: ./data/images_classic/
              imglist_pth: ./data/benchmark_imglist/mnist/test_cifar10.txt
            dictitems:
              data_dir: ./data/images_classic/
              imglist_pth: ./data/benchmark_imglist/mnist/test_cifar10.txt
          tin: !!python/object/new:openood.utils.config.Config
            state:
              data_dir: ./data/images_classic/
              imglist_pth: ./data/benchmark_imglist/mnist/test_tin.txt
            dictitems:
              data_dir: ./data/images_classic/
              imglist_pth: ./data/benchmark_imglist/mnist/test_tin.txt
          places365: !!python/object/new:openood.utils.config.Config
            state:
              data_dir: ./data/images_classic/
              imglist_pth: ./data/benchmark_imglist/mnist/test_places365.txt
            dictitems:
              data_dir: ./data/images_classic/
              imglist_pth: ./data/benchmark_imglist/mnist/test_places365.txt
  network: !!python/object/new:openood.utils.config.Config
    state:
      name: resnet50
      num_classes: 10
      image_size: 28
      pretrained: true
      checkpoint: ./imagenet_resnet50_base_e30_lr0.001_randaugment-2-9/s0/best_epoch27_acc0.7668.ckpt
      num_gpus: 1
    dictitems:
      name: resnet50
      num_classes: 10
      image_size: 28
      pretrained: true
      checkpoint: ./imagenet_resnet50_base_e30_lr0.001_randaugment-2-9/s0/best_epoch27_acc0.7668.ckpt
      num_gpus: 1
  exp_name: mnist_resnet50_test_ood_ood_msp_default/s0/ood
  output_dir: ./results/
  save_output: true
  merge_option: default
  mark: default
  seed: 0
  num_gpus: 1
  num_workers: 2
  num_machines: 1
  machine_rank: 0
  preprocessor: !!python/object/new:openood.utils.config.Config
    state:
      name: base
    dictitems:
      name: base
  pipeline: !!python/object/new:openood.utils.config.Config
    state:
      name: test_ood
    dictitems:
      name: test_ood
  trainer: !!python/object/new:openood.utils.config.Config
    state:
      name: base
    dictitems:
      name: base
  evaluator: !!python/object/new:openood.utils.config.Config
    state:
      name: ood
      ood_scheme: ood
    dictitems:
      name: ood
      ood_scheme: ood
  optimizer: !!python/object/new:openood.utils.config.Config
    state:
      name: sgd
      num_epochs: 60
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0005
    dictitems:
      name: sgd
      num_epochs: 60
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0005
  recorder: !!python/object/new:openood.utils.config.Config
    state:
      name: base
      save_all_models: false
      save_scores: true
      save_csv: true
    dictitems:
      name: base
      save_all_models: false
      save_scores: true
      save_csv: true
  postprocessor: !!python/object/new:openood.utils.config.Config
    state:
      name: msp
      APS_mode: false
    dictitems:
      name: msp
      APS_mode: false
